franka:
  controller_manager:
    ros__parameters:
      update_rate: 1000 # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

  joint_trajectory_controller:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3      
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 1000.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false