joint_limits:
  fr3_joint1:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint2:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint3:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint4:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint5:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint6:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint7:
    has_acceleration_limits: true
    max_acceleration: 5.0