joint_limits:
  joint_1:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_2:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_3:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_4:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_5:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_6:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint1:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint2:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint3:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint4:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint5:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint6:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint7:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_b:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_e:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_l:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_r:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_u:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_s:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_t:
    has_acceleration_limits: true
    max_acceleration: 5.0
  shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0