planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  joint_state_topic: "/joint_states"
  attached_collision_object_topic: "/planning_scene_monitor"
  publish_planning_scene_topic: "/publish_planning_scene"
  monitored_planning_scene_topic: "/monitored_planning_scene"
  wait_for_initial_state_timeout: 10.0

planning_scene_monitor_parameters:
  publish_planning_scene: false
  publish_geometry_updates: false
  publish_state_updates: false
  publish_transforms_updates: false
  publish_robot_description: false
  publish_robot_description_semantic: false

planning_pipelines:
  pipeline_names: ["ompl"]

use_sim_time: true

# Default
fanuc_arm:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: ompl
    planner_id: RRTConnectkConfigDefault
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0
    planning_time: 1.0